memory_limit = 512M
upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 600
max_input_time = 600
max_input_vars = 10000

# OPcache Optimization
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 64
opcache.max_accelerated_files = 30000
opcache.validate_timestamps = 0
opcache.save_comments = 1
